<a href="https://colab.research.google.com/github/rajeevfromkrec/NLP/blob/master/Text_preprocessing_with_sklearn_and_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
text=['The quick brown fox jumped over the lazy dog']

In [3]:
vectorizer= CountVectorizer()

In [5]:
vectorizer.fit(text)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [6]:
print(vectorizer.vocabulary_)

{'the': 7, 'quick': 6, 'brown': 0, 'fox': 2, 'jumped': 3, 'over': 5, 'lazy': 4, 'dog': 1}


In [7]:
vector= vectorizer.transform(text)

In [10]:
print(vector.toarray())

[[1 1 1 1 1 1 1 2]]


In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
text= ["The quick brown fox jumped over the lazy dog.", "The dog.", "The fox"]
vectorizer.fit(text)
print(vectorizer.vocabulary_)
vector=vectorizer.transform(text)
print(vector.toarray())

{'the': 7, 'quick': 6, 'brown': 0, 'fox': 2, 'jumped': 3, 'over': 5, 'lazy': 4, 'dog': 1}
[[0.36388646 0.27674503 0.27674503 0.36388646 0.36388646 0.36388646
  0.36388646 0.42983441]
 [0.         0.78980693 0.         0.         0.         0.
  0.         0.61335554]
 [0.         0.         0.78980693 0.         0.         0.
  0.         0.61335554]]


In [17]:

# split into words
#removes punctuations
#covert text into lower case
from keras.preprocessing.text import text_to_word_sequence
text = 'The quick brown fox jumped over the lazy dog.'
result=text_to_word_sequence(text)
print(result)

['the', 'quick', 'brown', 'fox', 'jumped', 'over', 'the', 'lazy', 'dog']


In [22]:
from keras.preprocessing.text import Tokenizer

docs = ['Well done!', 'Good work', 'Great effort', 'nice work', 'Excellent!']

t=Tokenizer()

t.fit_on_texts(docs)

print(t.word_index)

result=t.texts_to_matrix(docs,mode='count')
print(result)

{'work': 1, 'well': 2, 'done': 3, 'good': 4, 'great': 5, 'effort': 6, 'nice': 7, 'excellent': 8}
[[0. 0. 1. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [24]:
!wget http://www.cs.cornell.edu/people/pabo/movie-review-data/review_polarity.tar.gz

--2020-07-25 13:18:49--  http://www.cs.cornell.edu/people/pabo/movie-review-data/review_polarity.tar.gz
Resolving www.cs.cornell.edu (www.cs.cornell.edu)... 132.236.207.20
Connecting to www.cs.cornell.edu (www.cs.cornell.edu)|132.236.207.20|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3127238 (3.0M) [application/x-gzip]
Saving to: ‘review_polarity.tar.gz’

review_polarity.tar 100%[===================>]   2.98M  3.55MB/s    in 0.8s    

2020-07-25 13:18:50 (3.55 MB/s) - ‘review_polarity.tar.gz’ saved [3127238/3127238]



In [25]:
!ls

review_polarity.tar.gz	sample_data


In [44]:
!tar -xzf review_polarity.tar.gz

In [ ]:
!ls -lrt

In [ ]:
!ls

In [67]:
%cd ..

/content


In [69]:
def read_doc(filename):
  file= open(filename, 'r')
  text=file.read()
  file.close()
  return text